import Head from 'next/head'
import { FC, PropsWithChildren } from 'react'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'

interface Props {
  children: JSX.Element | JSX.Element[]
}

export const MainLayout: FC<PropsWithChildren<Props>> = ({ children }) => {

  // console.log(page);

  return (
    <>
      <Head>
        <title>Cromatica - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>
        
        { children }
        
      </main>
    </>

  )
}
